# syntax=docker/dockerfile:1
#FROM ubuntu:22.04
FROM busybox
MAINTAINER Allan-Nava
#
#ENV DEBIAN_FRONTEND noninterac1tive
ENV TZ=Etc/UTC
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
ENV HOME /home
#
WORKDIR /home
#
#WORKDIR /app
COPY . .
RUN bash -x build.sh
#
RUN rm -R /home/FFmpeg
RUN mv /home/bin/ffmpeg /usr/bin
RUN mv /home/bin/ffprobe /usr/bin
#
CMD ["/bin/bash"]